--1. Retrieve the customers who have placed orders with a total amount greater than $10000.--

CREATE VIEW high_value_customers AS 
SELECT 
	c.prefix || ' ' || c.firstname || ' ' || c.lastname fullname, 
	SUM(p.productprice * t.orderquantity) totalamount 
FROM totalsales t 
JOIN product p 
	ON t.productkey = p.productkey 
JOIN customer c 
	ON t.customerkey = c.customerkey 
GROUP BY c.customerkey, fullname 
HAVING SUM(p.productprice * t.orderquantity) > 10000;

--2. Retrieve the total revenue and total orders generated by each product category --

CREATE VIEW category_revenue_orders AS
SELECT 
	pc.categoryname, 
	SUM(p.productprice * t.orderquantity) totalrevenue, 
	COUNT(t.ordernumber) totalorders
FROM pcat pc
JOIN subcat sc
	ON pc.productcategorykey = sc.productcategorykey
JOIN product p
	ON sc.productsubcategorykey = p.productsubcategorykey 
LEFT JOIN totalsales t 
ON t.productkey = p.productkey 
GROUP BY pc.categoryname;

--3. Retrieve the names of products and their categories for products with a selling price greater than the average selling price of all products.- SQ--

CREATE VIEW products_above_avg_price AS
SELECT
	 p.productname,
	 pc.categoryname
FROM product p
JOIN subcat sc
	ON p.productsubcategorykey = sc.productsubcategorykey
JOIN pcat pc
	ON sc.productcategorykey = pc.productcategorykey
WHERE p.productprice > (SELECT AVG (productprice) FROM product);

--4. How many customers have placed orders in “Canada”? List the customer names - SQ --

CREATE VIEW canadian_customers AS
SELECT
    c.prefix || ' ' || c.firstname || ' ' || c.lastname fullname,
    COUNT(*) OVER() canadiancustomers
FROM customer c
JOIN totalsales ts
    ON c.customerkey = ts.customerkey
JOIN territory t
    ON ts.territorykey = t.salesterritorykey
WHERE t.country = 'Canada'
GROUP BY c.customerkey, fullname
ORDER BY fullname;

--5. Find the 10 products that have been returned the most. How much money was generated by these products? - SQ--

CREATE VIEW top_returned_products AS
SELECT
    p.productname,
    r.total_returns,
    SUM(ts.orderquantity * p.productprice) total_revenue
FROM (
    SELECT
        r.productkey,
        SUM(r.returnquantity) total_returns
    FROM return r
    GROUP BY r.productkey
    ORDER BY total_returns DESC
    LIMIT 10
) r
JOIN product p
    ON r.productkey = p.productkey
LEFT JOIN totalsales ts
    ON p.productkey = ts.productkey
GROUP BY p.productname, r.total_returns
ORDER BY r.total_returns DESC;

--6. Get a list of customers who have placed orders in more than one territory.--

CREATE VIEW multi_territory_customers AS
SELECT
	c.prefix || ' ' || c.firstname || ' ' || c.lastname fullname
FROM customer c
JOIN totalsales ts
	ON c.customerkey = ts.customerkey
JOIN territory t
	ON ts.territorykey = t.salesterritorykey
WHERE c.prefix || ' ' || c.firstname || ' ' || c.lastname IS NOT NULL
GROUP BY c.customerkey, fullname
HAVING COUNT (salesterritorykey) > 1;

--7. Retrieve the product names and their corresponding sub-categories for products that have been ordered at least 10 times.--
CREATE VIEW frequently_ordered_product AS
SELECT
	 p.productname,
	 sc.subcategoryname
FROM product p
JOIN subcat sc
	ON p.productsubcategorykey = sc.productsubcategorykey
JOIN totalsales ts
	ON p.productkey = ts.productkey
GROUP BY  p.productname, sc.subcategoryname
HAVING 	SUM (ts.orderquantity) >= 10;

--8. List the customer names who have placed orders after 2021. What is the distribution of their occupation?--

CREATE VIEW customers_post_2021 AS
SELECT
	DISTINCT c.customerkey,
	c.prefix || ' ' || c.firstname || ' ' || c.lastname fullname
FROM customer c
JOIN totalsales ts
	ON c.customerkey = ts.customerkey
WHERE ts.orderdate >= '2022/01/01';

CREATE VIEW customersocc_post_2021 AS
SELECT
    c.occupation,
    COUNT(DISTINCT c.customerkey) num_customers
FROM customer c
JOIN totalsales ts
    ON c.customerkey = ts.customerkey
WHERE ts.orderdate >= '2022-01-01'
GROUP BY c.occupation
ORDER BY num_customers DESC;

--9. Get a list of products and their corresponding order quantities for products that have been ordered at least once. --

CREATE VIEW products_ordered AS
SELECT
p.productname,
	SUM (ts.orderquantity) orders
FROM product p
JOIN totalsales ts
	ON p.productkey = ts.productkey
GROUP BY p.productname
HAVING SUM (ts.orderquantity) >= 1;

--10.Retrieve the product names that start with the letter "C" or “H” and are from the "Clothing" category.--

CREATE VIEW clothing_products_C_H AS
SELECT
	 p.productname
FROM product p
JOIN subcat sc
	ON p.productsubcategorykey = sc.productsubcategorykey
JOIN pcat pc
	ON sc.productcategorykey = pc.productcategorykey
WHERE (p.productname LIKE 'C%' OR p.productname LIKE 'H%') AND pc.categoryname = 'Clothing';

--11.Retrieve the product names that have been ordered in the ‘United States’ or "Australia".--

CREATE VIEW products_us_au AS
SELECT
	DISTINCT p.productname
FROM product p
JOIN totalsales ts
	ON p.productkey = ts.productkey
JOIN territory t
	ON ts.territorykey = t.salesterritorykey
WHERE t.country = 'United States' OR  t.country =  'Australia';

--12.Find the customer names who have placed orders with a total amount greater than the average total amount of orders. – SQ--

CREATE VIEW customers_above_avg_orders AS
SELECT
    c.prefix || ' ' || c.firstname || ' ' || c.lastname fullname,
    SUM(ts.orderquantity * p.productprice) total_amount
FROM customer c
JOIN totalsales ts 
    ON c.customerkey = ts.customerkey
JOIN product p 
    ON ts.productkey = p.productkey
GROUP BY c.customerkey, fullname
HAVING SUM(ts.orderquantity * p.productprice) > (
    SELECT AVG(customer_total)
    FROM (
        SELECT SUM(ts2.orderquantity * p2.productprice) customer_total
        FROM customer c2
        JOIN totalsales ts2
            ON c2.customerkey = ts2.customerkey
        JOIN product p2
            ON ts2.productkey = p2.productkey
        GROUP BY c2.customerkey)
);

--13.Retrieve the top 5 customers who have placed the highest number of orders, along with their order counts.--

CREATE VIEW top_customers_by_orders AS
SELECT
    c.prefix || ' ' || c.firstname || ' ' || c.lastname fullname,
    COUNT(ts.ordernumber) order_count
FROM customer c
JOIN totalsales ts
    ON c.customerkey = ts.customerkey
GROUP BY  c.customerkey, fullname
ORDER BY order_count DESC
LIMIT 5;

--14.List the customers who have placed orders within the last 6 months (consider the last date in the data)--

CREATE VIEW recent_customers_6months AS
SELECT DISTINCT
    c.customerkey,
    c.prefix || ' ' || c.firstname || ' ' || c.lastname fullname
FROM customer c
JOIN totalsales ts
    ON c.customerkey = ts.customerkey
WHERE ts.orderdate > (
    SELECT MAX(ts2.orderdate) - INTERVAL '6 months'
    FROM totalsales ts2
)

--15. We want to reach out to our best customers in 2022. Can you get emails of Top 50 customers based on revenue?--

CREATE VIEW top50_customers_2022 AS
SELECT
	c.emailaddress,
	SUM (p.productprice * ts.orderquantity) revenue
FROM customer c
JOIN totalsales ts
	ON c.customerkey = ts.customerkey
JOIN product p
	ON ts.productkey = p.productkey
WHERE ts.orderdate >= '2022/01/01'
GROUP BY c.emailaddress
ORDER BY revenue DESC
LIMIT 50;
